
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-svc
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-svc
  template:
    metadata:
      labels:
        app: catalog-svc
    spec:
      containers:
      - name: catalog-svc
        image: acraksworkshopdev.azurecr.io/catalog-svc:v1.0.0 # {"$imagepolicy": "flux-system:catalog-svc"}
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 5
