
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: apps-update
  namespace: flux-system
spec:
  checkout:
    gitRepositoryRef:
      name: platform # Change to your Flux GitRepository name
  commit:
    authorName: fluxcdbot
    authorEmail: fluxcdbot@users.noreply.github.com
    messageTemplate: "chore: update images"
  interval: 1m
  update:
    strategy: Setters
    path: ./deploy/k8s
